apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-angular-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-angular-app
  template:
    metadata:
      labels:
        app: my-angular-app
    spec:
      containers:
        - name: my-angular-app
          image: your-dockerhub-username/my-angular-app:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
